from glob import glob
from os.path import basename,join
from os import system
import pandas as pd
import os.path
from numpy import log2,median
import gzip

try:
    from itertools import izip_longest
except ImportError: 
    from itertools import zip_longest as izip_longest




configfile: "config/config.yaml"

sampleinfo = pd.read_table(config["sampleTable"])
SAMPLES=list(sampleinfo.loc[:,"sampleid"])
sample2fastq = {}
for i in range len(SAMPLES):
    sample2fastq[sampleinfo["sampleid"][i]] = {'r1': sampleinfo["R1"][i],'r2': sampleinfo["R2"][i]}


if config["aligner"] in ["STAR","star"]:
    system("mkdir -p results/star2ndpass/tmp")

rule all:
    input:
        "results/stringtie/stringtie_merged_wCDSfeatures.gff3"
    default_target: True


include: "rules/star.smk"
include: "rules/stringtie.smk"
include: "rules/transdecoder.smk"
include: "rules/add_cds.smk"
if config["StarIndexExists"] == False:
    include: "rules/starindex.smk"
