from glob import glob
from os.path import basename
from os import system
import pandas as pd

configfile: "config/config.yaml"

sampleinfo = pd.read_table(config["sampleTable"])
SAMPLES=list(sampleinfo.loc[:,"sampleid"])


if config["aligner"] in ["STAR","star"]:
    system("mkdir -p star2ndpass/tmp")


rule all:
    input:
        "transdecoder/stringtie_cdna.fa.transdecoder_dir/longest_orfs.cds.best_candidates.gff3.revised_starts.gff3"
    default_target: True

include: "rules/star.smk"
include: "rules/stringtie.smk"
include: "rules/transdecoder.smk"
