from glob import glob
from os.path import basename
from os import system
import pandas as pd
import os.path

configfile: "config/config.yaml"

sampleinfo = pd.read_table(config["sampleTable"])
SAMPLES=list(sampleinfo.loc[:,"sampleid"])


if config["aligner"] in ["STAR","star"]:
    system("mkdir -p star2ndpass/tmp")


if config["include_ncrnas"] ==True:
    rule all:
        input:
            "transdecoder/stringtie_transdecoder_genomecoords_ncRNAincluded.gff3"
        default_target: True
else:
    rule all:
        input:
            "transdecoder/stringtie_transdecoder_genomecoords.gff3"
        default_target: True



include: "rules/star.smk"
include: "rules/stringtie.smk"
include: "rules/transdecoder.smk"
include: "rules/ncrnainclude.smk"
