executor: slurm
use-conda: True
jobs: 100
latency-wait: 100
retries: 0

set-threads:
    star_1stpass: 8
    star_2ndpass: 8

set-resources:
    # STAR spliced-alignment    
    star_1stpass:
        nodes: 1
        mem_mb: 64000
        slurm_partition: "shared"
        runtime: 1920
    star_2ndpass:
        nodes: 1
        mem_mb: 64000
        slurm_partition: "shared"
        runtime: 1920
