executor: slurm
use-conda: True
jobs: 100
latency-wait: 100
retries: 0

set-threads:
    star_1stpass: 8
    star_2ndpass: 8

set-resources:
    # STAR spliced-alignment    
    star_1stpass:
        nodes: 1
        ntasks: 1
        threads: 8
        mem_mb: 64000
        slurm_partition: "shared"
        runtime: 1920
    star_2ndpass:
        nodes: 1
        ntasks: 1
        threads: 8
        mem_mb: 64000
        slurm_partition: "shared"
        runtime: 1920
    samsort_star:
        nodes: 1
        ntasks: 1
        threads: 12
        mem_mb: 24000
        slurm_partition: "shared"
        runtime: 360
    stringtie:
        nodes: 1
        ntasks: 1
        threads: 16
        mem_mb: 32000
        slurm_partition: "shared"
        runtime: 720
    stringtie_merge:
        nodes: 1
        ntasks: 1
        threads: 1
        mem_mb: 20000
        slurm_partition: "shared"
        runtime: 360

